discord-bot:
  # Get token from https://discord.dev/
  # Make sure you have enabled Discord Intents
  bot-token: "" # Leave blank if you do not want to use discord integration
  # ID of a text channel where all messages will be displayed
  channel-id: 0000000000
  # List of activities you can type in: PLAYING, COMPETING, LISTENING, STREAMING, WATCHING
  bot-activity: PLAYING
  # You can type here anything. For example: minecraft (Result: playing minecraft)
  bot-activity-text: "Minecraft"
  # What online status will have bot. List of them: ONLINE, IDLE, DO_NOT_DISTURB, INVISIBLE, OFFLINE
  bot-status: ONLINE

messages:
  no-permission: "&cYou do not have permission to do that"
  config-reload: "&aConfig was reloaded in: %s ms" # %s is a placeholder that displays time

database:
  type: h2
  h2:
    file: ./plugins/StaffRelay/staffrelay
  mysql:
    host: localhost
    port: 3306
    database: staffrelay
    username: root
    password: password
  sqlite:
    file: ./plugins/StaffRelay/staffrelay.db